# 
#
Import("env")
import os
import sys

print >> sys.stderr, "pkgsurl=%s" % env['pkgsurl']

macrodir = env['prefix'] + '/buildtemplates/macros'
m4flags = "-DTHEBASEURL=%s -DMACRODIR=%s" % (env['pkgsurl'], macrodir)
print "m4flags:", m4flags

env.M4("m4deploy", "m4deploy.m4", M4FLAGS=m4flags)

for cmd in "lsstpkg mksandbox mkmanifest setallcurrent.sh m4deploy".split():
    env.Command("../bin/"+cmd, cmd, [Copy('$TARGET', '$SOURCE'),
                                     Chmod('$TARGET', 0755)])


